### ISSUE TITLE
-o option works in an unexpected way

### ISSUE THREAD

**Issue by AMDmi3** [ansilove/ansilove#11]
In most utils, ```-o <filename>``` makes output written to ```<filename>```, though ansilove instead writes to ```<filename>.png```. IMO that's POLA violation which does not allow to specify exact output filename and should be fixed.

**Comment by fcambus** [comment]
Yes, you are correct. I think I introduced the regression during the getopt handling refactor.

@ByteProject mentioned he will take care of the issue.

**Comment by ByteProject** [comment]
I just published version 3.0.6, which is dealing with the issue. New behaviour for `-o <filename> ` is the output file being written to `<filename>` without `.png` appendix. Thanks for reporting.
