### ISSUE TITLE
Segfault when unable to open output file

### ISSUE THREAD

**Issue by AMDmi3** [ansilove/ansilove#12]
[This](https://github.com/ansilove/ansilove/blob/master/src/loaders/ansi.c#L515) and possibly other places lack check for `file_Out == NULL` when it's not possible to open output file. Because of that ansilove would segfault if it fails to open output file.

**Comment by fcambus** [comment]
Indeed. This should be fixed, thanks for reporting.

There are still a lot of areas which could use some cleanups, we will get there hopefully.
