### ISSUE TITLE
Messages are written to stdout instead of stderr

### ISSUE THREAD

**Issue by AMDmi3** [ansilove/ansilove#13]
After #11 was fixed, I've expected ansilove to work with `-o /dev/stdout`, however while it does seem to correctly write png there, it also writes messages there, resulting in corrupted file. Would be nice to write messages to stderr so ansilove could be used in pipelines. It'd also be nice to support `-o -` as an alias for writing to stdout like many other apps do.

**Comment by AMDmi3** [comment]
:+1: Thank you!

**Comment by fcambus** [comment]
Thanks for reporting the issue.

I added am internal note for the '-' aliasing, we will see about implementing it. I also wanted to evaluate the possibility of allowing reading from stdin to be able to pipe stuff to ansilove, so it might happen as well.
