### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by fcambus** [ansilove/ansilove#15]
There is an initial Debian package here: https://anonscm.debian.org/cgit/collab-maint/ansilove.git/commit/?id=4b7074b0a2f03bbd1112f4373538f2fc62c8cab1

**Comment by alexmyczko** [comment]
404

**Comment by fcambus** [comment]
The package was created by Thomas Goirand (zigo) from Debian, but that was before the ansilove/libansilove split, so I'm not sure it would be helpful now even if it was still online.

**Comment by fcambus** [comment]
The package has been accepted into unstable: https://lists.debian.org/debian-devel-changes/2019/07/msg01268.html

Thanks @alexmyczko!
