### ISSUE TITLE
Suppress output?

### ISSUE THREAD

**Issue by Kirkman** [ansilove/ansilove#22]
Could a switch/option be added to suppress all output when performing conversions?

**Comment by fcambus** [comment]
Do you have any use case in mind?

**Comment by Kirkman** [comment]
Running it within a Python script from a cron job? I wouldn't want all the output to be emailed to me each time the cron job runs.

**Comment by fcambus** [comment]
Sounds reasonable, we could use the -q switch (quiet) to have silent output.

**Comment by bart-d** [comment]
i'd use it, but i would also expect that even with -q output errors will still go to STDERR

**Comment by fcambus** [comment]
So it took a while, but we finally have a -q option for information messages, and errors continue to be sent to stderr. This should make everyone happy :-)

I will tag `4.0.3` soon, which will have those changes.
