### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by valacar** [ansilove/ansilove#24]
There seems to be a large amount of code missing. Looking at version 4.0.0 (master) the src directory has just 15.8k worth of code in it, where as version 3.0.9 has 647k. Missing the whole src/loaders/ directory, ansilove.h, explode.\*, fonts.c, main.c, output.\* and maybe some others.

Also, compiling version 3.0.9 works just fine, but with 4.0.0, CMake complains about missing variables called ANSILOVE_INCLUDE_DIRS and ANSILOVE_LIBRARIES and stops.

**Comment by bart-d** [comment]
In this version ansilove was split into a library and the tool. Compile and install libansilove first.

https://github.com/ansilove/libansilove

**Comment by valacar** [comment]
Oh, sorry, I was assuming it was like the last version. Thanks, I got it working now.
