### ISSUE TITLE
Number of comments is passed as a boolean?

### ISSUE THREAD

**Issue by andyherbert** [ansilove/ansilove#25]
I believe this should be if (readComments(file, record->comment_lines, record->comments))

https://github.com/ansilove/ansilove/blob/0ecb0167a8b0dbc4c0649ff634d92962b3da878e/src/sauce.c#L94

**Comment by fcambus** [comment]
Thanks for pointing this out, it was obviously wrong.

Fixed in 54dc52fb9bf775b41191a277787110ac2bfc7730.
