### ISSUE TITLE
Rendering with transparent mode and >=2 scaling factor breaks transparent background

### ISSUE THREAD

**Issue by corcoran** [ansilove/ansilove#28]
ansilove: 4.0.3
libansilove 1.1.4

Rendering with a regular 1x scaling factor works as intended but when using -r or -R 2-8 it seems to use the first ANSI color as the background.

Attached results of:
`ansilove -r -m transparent tk-droid.ans -o tk-droid-r2-transparent.png`
`ansilove -m transparent tk-droid.ans -o tk-droid-transparent.png`

![tk-droid-transparent](https://user-images.githubusercontent.com/1402817/65906690-f8c58200-e390-11e9-8990-c8da350f3615.png)
![tk-droid-r2-transparent](https://user-images.githubusercontent.com/1402817/65906692-f8c58200-e390-11e9-809f-49d6535378e6.png)

**Comment by fcambus** [comment]
Indeed, thanks for reporting the issue.

This should be fixed in latest libansilove master, let me know if it solves the issue for you.

**Comment by corcoran** [comment]
Fixed! Thanks my friend
