### ISSUE TITLE
Amiga renderer occasionally produces underlines

### ISSUE THREAD

**Issue by ByteProject** [ansilove/ansilove#3]
Here is a bug that is quite hard to explain. Sometimes, the Amiga renderer fails to render properly. Occurs when rendering a file with flag "amiga" and one of the Amiga fonts. AnsiLove/C generates underlines where there are not intended to go. Even more weird is the fact that sometimes it works, and sometimes it just doesn't. For instance, you can render a file and it looks fine. Repeat the rendering process a few times and you might encounter the issue. A photo of how the bug looks like is available here http://cl.ly/image/3J0X0T2w2x0o and a great example file for testing is available here http://cl.ly/183O0837303U

**Comment by fcambus** [comment]
For the record, the file used to produce the first screenshot can be found here : https://github.com/bricas/image-textmode/blob/master/corpus/input/AVE-AMI1.ASC

**Comment by fcambus** [comment]
Closing this as support for drawing bold, italics and underline characters for Amiga fonts has been removed.

Might be reimplemented cleanly using font dumps in the future, at least for bold and underline characters.
