### ISSUE TITLE
Some characters not rendering properly

### ISSUE THREAD

**Issue by rroels** [ansilove/ansilove#33]
Hi!

Thank you for this great tool. I have the issue that some characters don't render properly in ansilove while it works fine in Ascension. I tried every supported font but it doesn't seem to matter. 

As an example, this [input file](https://github.com/ansilove/ansilove/files/4601487/out.txt) results in this [image](https://user-images.githubusercontent.com/4035260/81446586-7d744c00-917b-11ea-8f5a-af1bef984822.png). However, in the terminal, my text editor and Ascension the borders of the boxes are rendered properly like [this](https://user-images.githubusercontent.com/4035260/81446816-ce844000-917b-11ea-9bf0-861555023c04.png).

In case you're wondering what I'm doing, I'm trying to render terminal output to images by doing something like this:
`tmux capture-pane -p  -e > out.txt && ansilove -o out.png out.txt`

I have to admit, I'm not a font/ansi/charset expert so this might be a dumb question. Any feedback would still be appreciated.

Thank you for your time.

**Comment by bart-d** [comment]
out.txt contains Unicode characters while Ansilove will only convert ASCII characters.

You might be able to force tmux to output ASCII by unsetting LC_CTYPE, however if the application you are running relies on UTF-8 characters, they will be converted to underscores.

**Comment by rroels** [comment]
Ok, thank you for your answer!
