### ISSUE TITLE
[Feature] Add option to use SAUCE info for rendering hints

### ISSUE THREAD

**Issue by bricas** [ansilove/ansilove#35]
The primary use case for pulling the SAUCE info would be for odd-width ansi rendering. As it stands, a user must specify the width manually. Allowing the info to be pulled automatically would simplfy the rendering process in a number of cases.

Note: there are chances of false positives, but the information currently seen in the "wild" would help far more than it would hurt.

This may require a little discussion, but i'm sure **width** is the most useful bit of information available. There are other bits available -- font name[(v00.5 SAUCE only), for example, could be handy, but perhaps this should be focused on width for now.

**Comment by fcambus** [comment]
Yes, I think this makes. I was relunctant to use the information by default, but adding a switch to
enable this conditionally makes sense, and I think we should go ahead with the proposal.

**Comment by bart-d** [comment]
SAUCE/ansilove font mapping

  "IBM VGA" => "80x25",
  "IBM VGA50" => "80x50",
  "IBM VGA 437" => "80x25",
  "IBM VGA50 437" => "80x50",
  "IBM VGA 775" => "baltic",
  "IBM VGA50 855" => "cyrillic",
  "IBM VGA 863" => "french-canadian",
  "IBM VGA 737" => "greek",
  "IBM VGA 869" => "greek-869",
  "IBM VGA 862" => "hebrew",
  "IBM VGA 861" => "icelandic",
  "IBM VGA 850" => "latin1",
  "IBM VGA 852" => "latin2",
  "IBM VGA 865" => "nordic",
  "IBM VGA 860" => "portuguese",
  "IBM VGA 866" => "russian",
  "IBM VGA 857" => "turkish",
  "Amiga MicroKnight" => "microknight",
  "Amiga MicroKnight+" => "microknight+",
  "Amiga mOsOul" => "mosoul",
  "Amiga P0T-NOoDLE" => "pot-noodle",
  "Amiga Topaz 1" => " topaz500",
  "Amiga Topaz 1+" => "topaz500+",
  "Amiga Topaz 2" => "topaz",
  "Amiga Topaz 2+" => "topaz+",

**Comment by bricas** [comment]
> For any type that does not match Character (with filetypes 1, 2, 3 and 8), BinaryText or XBIN I would bail out and warn the user that the filetype specified in SAUCE is not supported by ansilove.

So to be 100% clear -- do you actually mean filetypes 0, 1, 2 and 8?

The SAUCE spec (http://www.acid.org/info/sauce/sauce.htm) says 0 is ASCII, 1 is ANSI, 2 is ANSIMATION and 8 is Tundra.

Just want to confirm. Thanks.

**Comment by bart-d** [comment]
> So to be 100% clear -- do you actually mean filetypes 0, 1, 2 and 8?

Yes, correct

**Comment by fcambus** [comment]
Ansilove 4.1.3 has been released, with this feature enabled, thanks @bricas for the implementation!

**Comment by Sembiance** [comment]
With ansilove 4.1.3 and this pcboard file: [EEBRDM.PCB.zip](https://github.com/ansilove/ansilove/files/5247084/EEBRDM.PCB.zip)

Running `ansilove EEBRDM.PCB` produces a nice 640x240 image:
![a](https://user-images.githubusercontent.com/81436/93626477-78d56500-f9b1-11ea-8e19-9015ba0421e4.png)

However running `ansilove -S EEBRDM.PCB` produces a stretched 720x324 image:
![b](https://user-images.githubusercontent.com/81436/93626519-8854ae00-f9b1-11ea-9a15-3122ab766b20.png)

I'm not sure if this is a bug. If it's not a bug, could someone help me understand why it becomes stretch with the new '-S' flag?

**Comment by bricas** [comment]
With the SAUCE info, we get the following info:

```
        #000ARLSB
Flags: 0b00001101
```
per the docs: http://www.acid.org/info/sauce/sauce.htm#ANSiFlags

B: When 1, all 16 colors are supported for the character background.

LS: 10: Select 9 pixel font.

AR: 01: Image was created for a legacy device. When displayed on a device with square pixels, either the font or the image needs to be stretched.

So you're getting the 9px stretched aspect.

**Comment by fcambus** [comment]
This is interesting as this file was created in 1995: https://16colo.rs/pack/fti-0695/EEBRDM.PCB

So this was before SAUCE 00.5 was released (November 2013), introducing those aspect ratio flags.

**Comment by bricas** [comment]
Oh! True 'nuff! Probably bad SAUCE then?

**Comment by fcambus** [comment]
Likely so, and that is precisely why getting options from SAUCE has to be optional and can never be the default :-)

**Comment by Sembiance** [comment]
Cool, thanks for the info!

**Comment by bart-d** [comment]
unrelated to the functionality in ansilove, the output is actually correct taking into account history. pretty much any artwork created approximately before 2000 was using legacy aspect ratio and 9px fonts due the use of CRT screen at the time. while the flags did not exist in 1995, they are the right ones to use for artwork created at that time. 16c will force both legacy aspect and 9px fonts for artworks created before 2000 as it represents how the works were perceived at that time.
