### ISSUE TITLE
XBin 512 char font problem

### ISSUE THREAD

**Issue by mkrueger** [ansilove/ansilove#38]
I made a real masterpiece using the .xb format and wanted to convert it to a nice png - unfortunately ansilove doesn't read it correctly :(

[test.zip](https://github.com/ansilove/ansilove/files/8288484/test.zip)

Seems that extended fonts are not correctly implemented in ansilove - or maybe my implementation is wrong. 
(I'm currently working on updating my ansi drawing tool)

However I tested it with an old DOS tool (SIMPLEXB.EXE from acdu0896) and it seems to work. 
FYI DOSBox doesn't render the colors correctly because they treat bit 3 as font selection AND high intensity bit. In case you want to try. Maybe that can be solved using a custom palette setting the intense colors to low values but that's not the real goal :).

Old VGA hardware only took bit 3 as font selector and reduced the choice of foreground colors to 0-7 - yeah funny limits.

It's not a real bug. I couldn't find any .xb file supporting extended character sets - I would be interested in getting any for testing purposes.

**Comment by bricas** [comment]
Would you mind attaching the output you're getting and a brief explanation of what it _should_ look like? Thanks.

**Comment by mkrueger** [comment]
Sure:

Left like it theoretical should be correct. Right what the old dos program looks in dosbox (as said it uses intense colors as foreground which is technically not correct behavior. However I don't have a DOS computer staying aronud. 
Middle is the output of ansilove. 

![XB512Picture](https://user-images.githubusercontent.com/341098/158945287-ee039cfd-10b1-45a5-bc05-712ebb45ae2b.png)

Technically XB can contain 2 fonts and the high intensitity bit choses the font to use in extended font mode - that's it. Unfortunately most programs seem not to implement that feature :/

**Comment by bricas** [comment]
Thanks for the details, I'll take a look as soon as I can. Cheers.

**Comment by bricas** [comment]
Sorry for the delay. I haven't looked at this stuff in a while and debugging is non-trivial :)

A few observations:

- It looks like the character data is being extracted as you expect. It's uncompressed, so it's pretty straight-forward. The images have the same "form" (colors and character locations) if you will.
- Given the images share the same "form", and given the structure of the XBin (HEADER -> FONT DATA -> IMAGE DATA [palette data is optional and not in your file]) it's reasonable to assume we're extracting the right chunk of data for the font.
- Also, not all characters are different from your version, so we know that at least _some_ of the font data was parsed as you expected.

FYI: I've run your file against my perl toolset (Image::TextMode) and got the same result as Ansilove.

Looking at the very first character (position 0,0) I see that it's character 127 (0x7f) -- so it's not even into the >256 char range.  If I do a line-by-line binary printout of character 127,  I get:

```
00000000
00000000
00000000
00000000
00010000
00111000
01101100
11000110
11000110
11000110
11111110
00000000
00000000
00000000
00000000
00000000
```
Which matches what I'm seeing in the Ansilove & Image::Textmode outputs.

I've attempted to debug your font by spitting out all of the chars. I'm not 100% confident in this output; it was a bit rushed -- but it looks good for a bunch of the characters!

![f](https://user-images.githubusercontent.com/18400/159618251-7222d13e-0b91-4078-9c3d-e76e08de1999.png)

That's all I've got -- does that help?

**Comment by mkrueger** [comment]
The character is just 1 byte so it can't be >255 - look at the attribute that switches the font to the 2nd one  - as said it's the high bit of the foreground color that switches the font.

**Comment by bricas** [comment]
![facepalm](https://user-images.githubusercontent.com/18400/162863459-9fde7706-ad2c-41aa-81a2-9760d3fb3b6b.gif)

Oh man. I can't believe that fact has eluded me for like, 20 years. Thanks :)

With that knowledge, I was able to fix my Perl code -- I'l turn my attention to ansilove now.

**Comment by bricas** [comment]
This is now fixed in libansilove. @fcambus will cut a release soon.

Thanks for letting us know about this issue! Cheers.

**Comment by mkrueger** [comment]
Thanks :). I always wanted to add support for that in the 90' to my ansi tool but nobody cared about - now ~25 years later it's super important - hahaha :).

It's just for completeness - nobody really did 512 char content AFAIK. When fedora 36 is final I'll continue on my ansi editor then at least it'll be possible to create content. Unfortunately I'm a lousy artist - can't even draw a straight line without youtube guide :(

Only needed that for my mailbox :).

Thanks for implementing that
