### ISSUE TITLE
Print log on stderr, i.e. different stream from stdout

### ISSUE THREAD

**Issue by poetaman** [ansilove/ansilove#39]
The name ``stderr`` is a historical misnomer, it was meant to be used as if it were ``stdlog``.

```
$ ansilove -s somefile.ans

...
...
...

Processed in 0.000048 seconds.
```

ansilove is currently printing ``Processed in 0.000048 seconds.`` on standard output stream instead if stderr. That makes it difficult to filter expected output from log. All unix utilities I know of print log on stderr to make life of users easier for filtering among other things... Thanks!

```
$ ansilove -v
AnsiLove/C 4.1.6 - ANSI / ASCII art to PNG converter
Copyright (c) 2011-2022 Stefan Vogt, Brian Cassidy, and Frederic Cambus.
```

**Comment by fcambus** [comment]
Thanks for your report, this is fixed in 6f391897939cd6629e4b1aade446b1f97ca3901b.
