### ISSUE TITLE
Output animated png with blink attribute

### ISSUE THREAD

**Issue by YulongNiu** [ansilove/ansilove#41]
Hi, 

I love ansilove, it is great. Just want to check: 

Can I convert .ANS to png with blink effect? 

I tried different options, but it did work. I give an example blow.

Raw .ANS file  [blink_test.ans.gz](https://github.com/ansilove/ansilove/files/11228111/blink_test.ans.gz)

Convert to animated png by Moebius 
![blink_test](https://user-images.githubusercontent.com/5742772/231923814-f5a4469b-a44b-49b4-b280-4a3e99c5df62.png)

Convert to png by ansilove 
```
ansilove -o blink_test_regular.png blink_test.ans
```
![blink_test_regular](https://user-images.githubusercontent.com/5742772/231924428-f62d3ce6-66be-499b-a73f-822f347796cb.png)

with `-i` option by ansilove

```
ansilove -i -o blink_test_iCE.png blink_test.ans
```
![blink_test_iCE](https://user-images.githubusercontent.com/5742772/231924807-41c66489-4d36-4127-bcb8-dbb548c9da5d.png)

**Comment by fcambus** [comment]
Blinking and animations are currently not supported.

Both are supported in [Ansilove.js](https://github.com/ansilove/ansilove.js) though.

**Comment by YulongNiu** [comment]
Thank your, I will try Ansilove.js.
