### ISSUE TITLE
Case conversion before opening file

### ISSUE THREAD

**Issue by gaffatape** [ansilove/ansilove#8]
Hi,

Thank you for writing ansilove. Awesome work!

I had to patch ansilove to convert an all uppercase file, because in `main.c:282` the extension part of the filename is converted to lower case before the file is being opened.

You could do case-insensitive string comparison instead, to avoid the malloc/copy/free. I don't know what I prefer myself, but this was my quick fix.

```diff
282c282,284
<         char *fext = strrchr(input, '.');
---
>         char *fext_ptr = strrchr(input, '.');
>         char *fext = malloc(strlen(fext_ptr)+1);
>         strcpy(fext, fext_ptr);
310a313,314
> 
>         free(fext);
```

Cheers!
gaffa

**Comment by gaffatape** [comment]
I guess another option, that I think I would prefer myself, is to open the file handle in the main function and pass the file handle to the loaders.

**Comment by fcambus** [comment]
Hello,

Glad you like Ansilove, and sorry for not answering erlier. Thanks for reporting the issue, I finally found some time to work on Ansilove again, and commit d42cf0c4464de829f45b2d8e24ac0af64bda0c33 should fix the issue.

Indeed, there is still a lot of code duplication resulting from the conversion from the PHP codebase to the C one, there are plans to move some of the file handling code in the main function.
